#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(std430, binding = 0) buffer noiseBuffer{
	int blockIDs[];
};

layout(std430, binding = 1) buffer distanceToAirBuffer {
	int distanceToAirMap[];
};

uniform int width;
uniform int height;
uniform int depth;

bool IsSolid(int x, int y, int z) {
    if (x < 0 || x >= width || y < 0 || y >= height || z < 0 || z >= depth) 
        return false; // Treat out-of-bounds as air
    int index = x + y * width + z * width * height;
    return blockIDs[index] >= 0;
}

void main(){
	uint xPos = gl_GlobalInvocationID.x;
	uint yPos = gl_GlobalInvocationID.y;
	uint zPos = gl_GlobalInvocationID.z;
	
	if(xPos >= uint(width) || yPos >= uint(height) || zPos >= uint(depth)) return;

	int x = int(xPos);
	int y = int(yPos);
	int z = int(zPos);
	uint index = xPos + (yPos) * uint(width) + zPos * uint(width) * uint(height);

	if (!IsSolid(int(xPos), int(yPos), int(zPos))) {
			distanceToAirMap[index] = 0;
			return;
	}
	for(uint i = 1; yPos + i < uint(height); i++){
		uint checkY = yPos + i;
		// Stop if we hit the top of the world
        if (checkY >= uint(height)){ distanceToAirMap[index] = 0; break;}
		if(!IsSolid(int(xPos), int(checkY), int(zPos))) {
            distanceToAirMap[index] = int(i);
            break;
        }
	}
}