#version 430 core

//Enable the 16-bit storage extension
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(std430, binding = 0) buffer noiseBuffer{
	uint16_t blockIDs[];
};

layout(std430, binding = 1) buffer distanceToAirBuffer {
	uint16_t distanceToAirMap[];
};

uniform int width;
uniform int height;
uniform int depth;

bool IsSolid(int x, int y, int z) {
    if (x < 0 || x >= width || y < 0 || y >= height || z < 0 || z >= depth) 
        return false; // Treat out-of-bounds as air
    int index = x + y * width + z * width * height;
    return uint(blockIDs[index]) > 0u;
}

void main(){
	uint xPos = gl_GlobalInvocationID.x;
	uint yPos = gl_GlobalInvocationID.y;
	uint zPos = gl_GlobalInvocationID.z;
	
	if(xPos >= uint(width) || yPos >= uint(height) || zPos >= uint(depth)) return;

	int x = int(xPos);
	int y = int(yPos);
	int z = int(zPos);
	uint index = xPos + (yPos) * uint(width) + zPos * uint(width) * uint(height);

	if (!IsSolid(int(xPos), int(yPos), int(zPos))) {
			distanceToAirMap[index] = uint16_t(0);
			return;
	}
	distanceToAirMap[index] = uint16_t(uint(height) - yPos);

	for(uint i = 1; yPos + i < uint(height); i++){
		uint checkY = yPos + i;
		if(!IsSolid(int(xPos), int(checkY), int(zPos))) {
			distanceToAirMap[index] = uint16_t(i);
			break;
		}
	}
}