#version 430 core

// Compute shader - one thread per cube
layout(local_size_x = 64) in;

layout(std430, binding = 0) buffer blockBuffer{
	int blockIDs[];
};

layout(std430, binding = 1) buffer TotalActiveCount {
	uint totalActiveCount;
};

layout(std430, binding = 2) buffer ActiveVoxelList {
    uint activeVoxels[]; 
};

layout(std430, binding = 3) buffer distanceToAirBuffer{
	int distanceToAirMap[];
};


uniform int width;
uniform int height;
uniform int depth;

bool IsSolid(int x, int y, int z) {
    if (x < 0 || x >= width || y < 0 || y >= height || z < 0 || z >= depth) 
        return false; // Treat out-of-bounds as air
    int index = x + y * width + z * width * height;
    return blockIDs[index] >= 0;
}

void main(){
	
	uint listIdx = gl_GlobalInvocationID.x;

	if (listIdx >= totalActiveCount) return;

	uint packedID = activeVoxels[listIdx];
	
	int x = int(packedID & 0x3FF);
	int y = int((packedID >> 10) & 0x3FF);
	int z = int((packedID >> 20) & 0x3FF);    

	

	if(!IsSolid(x,y,z)) return;

	int index = x + y * (width) + z * (width) * (height);
	int dist = distanceToAirMap[index];
	// Use a simple hash for noise if you don't have a texture
    float n = fract(sin(dot(vec2(x,z), vec2(12.9898, 45.164))) * 43758.5453);
    float threshold = 3.0 + (n * 5.0);
	if(distanceToAirMap[index] == 1){
		blockIDs[index] = 1;
		return;
	}

	else if(dist > 1 && float(dist) < threshold){
		blockIDs[index] = 2;
	}
}